services:
  - type: web
    name: mammamia-mfp
    env: docker
    dockerfilePath: ./mammamia/Dockerfile
    envVars:
      - key: TMDB_KEY
        value: da_inserire
      - key: PROXY
        value: da_inserire
      - key: FORWARDPROXY
        value: da_inserire
